### ISSUE TITLE
AttributeError: 'list' object has no attribute 'start_tick'

### ISSUE THREAD

**Issue by michaelkostal** [bobgonzalez/spEdit404#6]
I got the following error when trying to save a pattern

```
>w
enter bank > a
enter pad > 1
Traceback (most recent call last):
  File "spEdit.py", line 104, in <module>
    pattern = action_map[menu_choice](pattern)
  File "spEdit.py", line 62, in write_pattern_to_file
    write_binary(pattern, bank, pad)
  File "/spEdit404/binary_utilities.py", line 13, in write_binary
    notes = get_sorted_notes(pattern)
  File "/spEdit404/binary_utilities.py", line 21, in get_sorted_notes
    notes = sorted(notes, key=lambda n: n.start_tick)
  File "/spEdit404/binary_utilities.py", line 21, in <lambda>
    notes = sorted(notes, key=lambda n: n.start_tick)
AttributeError: 'list' object has no attribute 'start_tick'
```

**Comment by bobgonzalez** [comment]
Gotcha. I know what this is and will fix it this evening.

**Comment by bobgonzalez** [comment]
Resolved sorry about that!

**Comment by bobgonzalez** [comment]
Need to put some test around this function and some others to prevent breaking changes.

**Comment by michaelkostal** [comment]
Cool, thanks!
